<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_zlib_surrounded.TestZlibSurrounded-20230719210200" tests="1" file="test_zlib_surrounded.py" time="0.001" timestamp="2023-07-19T21:02:00" failures="1" errors="0" skipped="0">
	<testcase classname="test_zlib_surrounded.TestZlibSurrounded" name="test_zlib_surrounded" time="0.001" timestamp="2023-07-19T21:02:00" file="spec/construct/test_zlib_surrounded.py" line="8">
		<failure type="AssertionError" message="-287624 != -1"><![CDATA[Traceback (most recent call last):
  File "/tests/spec/construct/test_zlib_surrounded.py", line 11, in test_zlib_surrounded
    self.assertEqual(r.zlib.num, -1)
AssertionError: -287624 != -1
]]></failure>
	</testcase>
</testsuite>
