<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_combine_enum.TestCombineEnum-20200911172037" tests="1" file="test_combine_enum.py" time="0.001" timestamp="2020-09-11T17:20:37" failures="0" errors="1" skipped="0">
	<testcase classname="test_combine_enum.TestCombineEnum" name="test_combine_enum" time="0.001" timestamp="2020-09-11T17:20:37" file="spec/construct/test_combine_enum.py" line="8">
		<error type="NameError" message="name 'CombineEnum' is not defined"><![CDATA[Traceback (most recent call last):
  File "/home/travis/build/kaitai-io/ci_targets/tests/spec/construct/test_combine_enum.py", line 11, in test_combine_enum
    self.assertEqual(r.enum_u4, CombineEnum.Animal.pig)
NameError: name 'CombineEnum' is not defined
]]></error>
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
</testsuite>
