<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_repeat_until_complex.TestRepeatUntilComplex-20210403173753" tests="1" file="test_repeat_until_complex.py" time="0.003" timestamp="2021-04-03T17:37:53" failures="1" errors="0" skipped="0">
	<testcase classname="test_repeat_until_complex.TestRepeatUntilComplex" name="test_repeat_until_complex" time="0.003" timestamp="2021-04-03T17:37:53" file="spec/construct/test_repeat_until_complex.py" line="8">
		<failure type="AssertionError" message="&lt;built-in method values of Container object at 0x7f01cf761700&gt; != [1, 2, 3, 4]"><![CDATA[Traceback (most recent call last):
  File "/home/travis/build/kaitai-io/ci_targets/tests/spec/construct/test_repeat_until_complex.py", line 12, in test_repeat_until_complex
    self.assertEqual(r.first[0].values, [(0 + 1), 2, 3, 4])
AssertionError: <built-in method values of Container object at 0x7f01cf761700> != [1, 2, 3, 4]
]]></failure>
	</testcase>
</testsuite>
