<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_process_repeat_usertype.TestProcessRepeatUsertype-20210302200010" tests="1" file="test_process_repeat_usertype.py" time="0.001" timestamp="2021-03-02T20:00:10" failures="1" errors="0" skipped="0">
	<testcase classname="test_process_repeat_usertype.TestProcessRepeatUsertype" name="test_process_repeat_usertype" time="0.001" timestamp="2021-03-02T20:00:10" file="spec/construct/test_process_repeat_usertype.py" line="8">
		<failure type="AssertionError" message="346274796 != -1975704206"><![CDATA[Traceback (most recent call last):
  File "/home/travis/build/kaitai-io/ci_targets/tests/spec/construct/test_process_repeat_usertype.py", line 11, in test_process_repeat_usertype
    self.assertEqual(r.blocks[0].a, -1975704206)
AssertionError: 346274796 != -1975704206
]]></failure>
	</testcase>
</testsuite>
