<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" file="test_expr_bytes_ops.py" name="test_expr_bytes_ops.TestExprBytesOps-20191020011652" skipped="0" tests="1" time="0.001" timestamp="2019-10-20T01:16:52">
	<testcase classname="test_expr_bytes_ops.TestExprBytesOps" file="spec/python/test_expr_bytes_ops.py" line="8" name="test_expr_bytes_ops" time="0.001" timestamp="2019-10-20T01:16:52">
		<failure message="'P' != 80" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/travis/build/kaitai-io/ci_targets/tests/spec/python/test_expr_bytes_ops.py", line 12, in test_expr_bytes_ops
    self.assertEqual(r.one_first, 80)
AssertionError: 'P' != 80
]]>		</failure>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
