<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="test_nav_parent2.TestNavParent2-20180205010343" skipped="0" tests="1" time="0.001">
	<testcase classname="test_nav_parent2.TestNavParent2" name="test_nav_parent2" time="0.001">
		<error message="I/O operation on closed file" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "/home/travis/build/kaitai-io/ci_targets/tests/spec/python/test_nav_parent2.py", line 15, in test_nav_parent2
    self.assertEqual(r.tags[0].tag_content.content, "foo")
  File "/home/travis/build/kaitai-io/ci_targets/tests/compiled/python/nav_parent2.py", line 54, in tag_content
    _pos = io.pos()
  File "/home/travis/build/kaitai-io/ci_targets/runtime/python/kaitaistruct.py", line 76, in pos
    return self._io.tell()
ValueError: I/O operation on closed file
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
