<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="test_nav_parent3.TestNavParent3-20180205010317" skipped="0" tests="1" time="0.000">
	<testcase classname="test_nav_parent3.TestNavParent3" name="test_nav_parent3" time="0.000">
		<error message="I/O operation on closed file" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "/home/travis/build/kaitai-io/ci_targets/tests/spec/python/test_nav_parent3.py", line 12, in test_nav_parent3
    self.assertEqual(r.tags[0].name, "RAHC")
  File "/home/travis/build/kaitai-io/ci_targets/tests/compiled/python/nav_parent3.py", line 64, in tags
    _pos = self._io.pos()
  File "/home/travis/build/kaitai-io/ci_targets/runtime/python/kaitaistruct.py", line 76, in pos
    return self._io.tell()
ValueError: I/O operation on closed file
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
